import { Provider } from './provider.base.js';

class MockProvider extends Provider {
  constructor(options = {}) {
    super();
    this.options = options;
  }

  async generateText(prompt, options = {}) {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 100));

    // Handle both string and object prompts
    const promptText =
      typeof prompt === 'string' ? prompt : JSON.stringify(prompt);

    // Return mock response based on prompt content
    if (
      promptText.includes('scaffold') ||
      promptText.includes('draft_scaffold')
    ) {
      return JSON.stringify(
        {
          title: 'Privacy-First Analytics for Startup Founders',
          sections: [
            {
              heading: 'Why Privacy Matters for Your Startup',
              bullets: [
                'Build customer trust from day one',
                'Comply with GDPR, CCPA, and emerging regulations',
                'Differentiate from Big Tech competitors',
              ],
            },
            {
              heading: 'Analytics Without Compromise',
              bullets: [
                'Track user behavior without personal data collection',
                'Get actionable insights while respecting privacy',
                'Reduce legal risk and compliance overhead',
              ],
            },
            {
              heading: 'Implementation Strategy',
              bullets: [
                'Choose privacy-first analytics tools',
                'Set up consent management properly',
                'Monitor and optimize performance',
              ],
            },
          ],
        },
        null,
        2
      );
    }

    if (
      promptText.includes('expand') ||
      promptText.includes('section_expand')
    ) {
      return "Privacy matters more than ever for startup founders. Building customer trust from day one isn't just good ethics—it's smart business. When users know you respect their data, they're more likely to engage deeply with your product. This trust translates directly into higher conversion rates, lower churn, and stronger word-of-mouth growth. Privacy-first analytics lets you understand user behavior without compromising on the values that matter to your customers.";
    }

    if (
      promptText.includes('rewrite') ||
      promptText.includes('rewrite_localize')
    ) {
      return 'This content has been rewritten for the specified audience, tone, and reading level using privacy-focused analytics principles.';
    }

    if (
      promptText.includes('summarize') ||
      promptText.includes('summarize_grounded')
    ) {
      return 'Executive Summary: This transcript discusses privacy-first analytics implementation strategies for startups. Key points include regulatory compliance, customer trust building, and technical implementation approaches. [Timestamp: 0:00-5:30]';
    }

    if (
      promptText.includes('repurpose') ||
      promptText.includes('repurpose_pack')
    ) {
      return JSON.stringify(
        {
          linkedin: {
            title: '🔒 Privacy-First Analytics: The Startup Advantage',
            content:
              "Smart founders are choosing privacy-first analytics. Here's why your startup should too...",
            hashtags: ['#PrivacyFirst', '#StartupLife', '#Analytics'],
          },
          twitter: {
            content:
              "Privacy-first analytics isn't just compliance—it's competitive advantage. 🚀\n\nYour customers will thank you. Your lawyers will thank you. Your growth metrics will thank you.\n\n#PrivacyFirst #StartupTips",
            thread: false,
          },
          email: {
            subject: 'Why Your Startup Needs Privacy-First Analytics',
            preview: 'Building trust while growing fast',
            content:
              'Dear Founder,\n\nEvery data point you collect is a promise to your users...',
          },
        },
        null,
        2
      );
    }

    return 'This is a mock response from the MockProvider. In a real implementation, this would be generated by an AI model based on your prompt.';
  }
}

export default MockProvider;
